//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class InputView
{
	public virtual EnterRebateHandler InputHandler
	{
		get;
		set;
	}

	public virtual TransactionHandler TransactionHandler
	{
		get;
		set;
	}

	public virtual GenRebateHandler GenRebateHandler
	{
		get;
		set;
	}

	public virtual RetunHandler RetunHandler
	{
		get;
		set;
	}

	public InputView(object EnterRebateHandler h, object TransactionHandler th, object GenRebateHandler gh, object ReturnHandler rh)
	{
	}

	public virtual void Transation_Onlick()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Return_Onclick()
	{
		throw new System.NotImplementedException();
	}

	public virtual void EnterRebate_Onlick()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GenRebate_Onlick()
	{
		throw new System.NotImplementedException();
	}

}

