//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Item : ItemI
{
	private float price
	{
		get;
		set;
	}

	private string name
	{
		get;
		set;
	}

	private int amount
	{
		get;
		set;
	}

	private bool returned
	{
		get;
		set;
	}

	public virtual string ToString()
	{
		throw new System.NotImplementedException();
	}

	public Item(object int a, object string name, object float price)
	{
	}

}

