//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SalesManager : TransactionHandler
{
	private int transactionID
	{
		get;
		set;
	}

	public virtual transactionObs transactionObs
	{
		get;
		set;
	}

	public virtual returnObs returnObs
	{
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public virtual void createTransaction()
	{
		throw new System.NotImplementedException();
	}

}

