//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Database : Manager
{
	private Dictionary<int,Transaction> transactions
	{
		get;
		set;
	}

	private Dictionary<int, Rebate> rebate
	{
		get;
		set;
	}

	public virtual TransactionI TransactionI
	{
		get;
		set;
	}

	public virtual Transaction getTransaction(object int id)
	{
		throw new System.NotImplementedException();
	}

	public virtual string generateRebate()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getTransaction()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getRebate()
	{
		throw new System.NotImplementedException();
	}

	public virtual void addTransaction()
	{
		throw new System.NotImplementedException();
	}

}

