//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Rebate
{
	private int rebateID
	{
		get;
		set;
	}

	private returned bool
	{
		get;
		set;
	}

	private date string
	{
		get;
		set;
	}

}

