//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class RebateManager : EnterRebateHandler, GenRebateHandler
{
	public void enterRebate(object sender, EventArgs e)
	{
		
	}

	public void genRebate(object sender, EventArgs e)
	{
		
	}

}

