//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class RebateManager : RebateHandler
{
    public RebateManager(ModelI d)
    {

    }

    public void register(Func<string> eRebate, Func<string> genRebate)
    {

    }

	public void enterRebate(object sender, EventArgs e)
	{
		
	}

	public void genRebate(object sender, EventArgs e)
	{
		
	}

}

