//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Project_4.GeneratedCode;

public class ReturnsManager
{
    public delegate void ReturnHandler(string n, int i);

    public ReturnHandler returnHandler;

    ReciptOutputView.Observer updateReturnsOutput;
    ModelI dataBase;

    public ReturnsManager(ModelI m)
    {
        dataBase = m;
        returnHandler = new ReturnHandler(returnItem);
    }

	public void returnItem(string name, int id)
	{
        Transaction t = dataBase.getTransaction(id);
       if( t.Items.ContainsKey(name) && t.Rebate == false)
        {
            Item i = t.Items[name];
            if(i.Amount>1)
            {
                i.Amount--; 
            }
            else
            {
                // t.Items.Remove(name);
                i.Amount = 0;
            }
        }
        //updateReturnsOutput
    }

    internal void register(ReciptOutputView.Observer run)
    {
        updateReturnsOutput = run;
    }
}

