//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Project_4.GeneratedCode;

public class ReturnsManager : RetunHandler
{
    public ReturnsManager(ModelI m)
    {

    }

	public void returnItem()
	{
		
	}

    internal void register(CustomerServiceOutputView.Observer run)
    {
        throw new NotImplementedException();
    }
}

