//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Project_4.GeneratedCode;

public class SalesManager
{
    public delegate void TransactionHandler(int id);
    public delegate void ItemHandler(int q, float p, string n);
    public delegate void EndTransactionHandler();

    public TransactionHandler transHandler;
    public ItemHandler itemHandler;
    public EndTransactionHandler endHandler;

    ReciptOutputView.Observer updateTransactionOutput;
    ModelI dataBase;
    Transaction currentTrans;

    public SalesManager(ModelI m)
    {
        dataBase = m;
        transHandler = new TransactionHandler(createTransaction);
        itemHandler = new ItemHandler(addItem);
        endHandler = new EndTransactionHandler(endTransaction);
    }

	public void createTransaction(int tNum)
	{
       currentTrans = new Transaction(tNum);
       
    }

    public void endTransaction()
    {
        dataBase.addTransaction(currentTrans); //add to db once transaction has ended?
        updateTransactionOutput(currentTrans.getID(), true);
    }

    public void addItem(int quantity, float price, string name)
    {
        if (currentTrans.Items.ContainsKey(name))
        {
            currentTrans.Items[name].Amount++;
        }
        else
        {
            currentTrans.Items.Add(name, new Item(name, price, quantity));
        }
        //updateTransactionOutput
    }

    internal void register(ReciptOutputView.Observer o)
    {
        updateTransactionOutput = o;
    }
}

