//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class SalesManager : TransactionHandler
{	
    public SalesManager(ModelI m)
    {

    }

	public void createTransaction(object sender, EventArgs e)
	{
		
	}

    public void register(Func<string> output)
    {

    }
}

