//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Transaction : TransactionI
{
	private List<Item> items
	{
		get;
		set;
	}

	private string date
	{
		get;
		set;
	}

	private int id
	{
		get;
		set;
	}

	public virtual ItemI ItemI
	{
		get;
		set;
	}

	public virtual Item Item
	{
		get;
		set;
	}

	public virtual string genReciept()
	{
		throw new System.NotImplementedException();
	}

	public Transaction(object int id)
	{
	}

	public virtual void addItem(object int a, object string n, object int p)
	{
		throw new System.NotImplementedException();
	}

}

